spring:
  application:
    name: springBoot_security_journey
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: Mahdi1472003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
